// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

namespace Server.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Server.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Year = 2000
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Volkswagem",
                            Model = "Golf",
                            Year = 2005
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Fiat",
                            Model = "Uno",
                            Year = 2012
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Mercedes-Benz",
                            Model = "A45",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "BMW",
                            Model = "550i",
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Chevrolet",
                            Model = "Cruze",
                            Year = 2001
                        });
                });

            modelBuilder.Entity("Server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (short)21,
                            FirstName = "Oliver",
                            LastName = "Oniper"
                        },
                        new
                        {
                            Id = 2,
                            Age = (short)30,
                            FirstName = "John",
                            LastName = "Lorks"
                        },
                        new
                        {
                            Id = 3,
                            Age = (short)45,
                            FirstName = "Chris",
                            LastName = "Mork"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
